[model]
name = "umamba"
variant = "enc"
source_root = ""
num_classes = 4
num_modalities = 4
img_size = [128, 128, 128]
num_stages = 6
features_per_stage = [32, 64, 128, 256, 320, 320]
kernel_sizes = [
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
]
strides = [
  [1, 1, 1],
  [2, 2, 2],
  [2, 2, 2],
  [2, 2, 2],
  [2, 2, 2],
  [2, 2, 2],
]
n_conv_per_stage = [2, 2, 2, 2, 2, 2]
n_conv_per_stage_decoder = [2, 2, 2, 2, 2]
conv_bias = true
deep_supervision = false
strict_img_size = true
initialize = true

[task]
loss = "dc_and_ce"

[data]
batch_size = 1
