[model]
name = "nestedformer"
num_classes = 4
num_modalities = 4
source_root = ""
image_size = [128, 128, 128]
out_channels = 3
fea = [16, 16, 32, 64, 128, 16]
window_size = [4, 4, 4]
pool_size = [[2, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2]]
self_num_layer = 2
token_mixer_size = 32
token_learner = true
strict_img_size = true

[task]
loss = "brats_sigmoid_region_dice"
