[model]
name = "nnunet"
num_classes = 4
num_modalities = 4
architecture = "plain_conv_unet"
num_stages = 6
features_per_stage = [32, 64, 128, 256, 320, 320]
kernel_sizes = [
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
  [3, 3, 3],
]
strides = [
  [1, 1, 1],
  [2, 2, 2],
  [2, 2, 2],
  [2, 2, 2],
  [2, 2, 2],
  [2, 2, 2],
]
n_conv_per_stage = [2, 2, 2, 2, 2, 2]
n_conv_per_stage_decoder = [2, 2, 2, 2, 2]
conv_bias = true
norm_op = "instance_norm"
nonlin = "leaky_relu"
deep_supervision = false

[task]
loss = "dc_and_ce"
