[model]
name = "slim_unetr"
num_classes = 4
num_modalities = 4
source_root = ""
embed_dim = 96
embedding_dim = 64
channels = [24, 48, 60]
blocks = [1, 2, 3, 2]
heads = [1, 2, 4, 4]
r = [4, 2, 2, 1]
dropout = 0.3

[task]
loss = "slim_unetr_focal_dice"
loss_gamma = 2.0
